# Generated by Django 4.1.4 on 2023-01-25 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
