# Generated by Django 4.1.4 on 2023-01-25 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0002_alter_publication_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
