# Generated by Django 4.1.4 on 2023-01-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0006_alter_profileuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='publication_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
