# Generated by Django 4.1.4 on 2023-01-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_publication_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
