# Generated by Django 4.1.4 on 2023-01-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_alter_publication_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_image',
            field=models.ImageField(default='blanco.jpg', upload_to=''),
        ),
    ]
